### ISSUE TITLE
Change slide 6 to point at a more up-to-date diagram of Hydra-Works

### ISSUE THREAD

**Issue by mjgiarlo** [samvera/samvera.github.io#1]
Current slide 6 is confusing:
- Has confusing "c/" and "o/" prefixes
- Has "GenericWork" instead of "Work"
- Typo: `s/Thubnail/Thumbnail/`
- Outdated term: `s/GenericFile/FileSet/`
- Outdated term: `s/Content/OriginalFile/`

I've made these corrections here, so feel free to grab a screenshot and use it: https://docs.google.com/drawings/d/1if47TYgEhqDLPh3D0026B_cBLa0BEAOpWPs8AqoQMZE/edit

**Comment by RudyOnRails** [comment]
I assume this outdated, and can be closed?
