### ISSUE TITLE
Create initial doc for "best practices" for writing documentation (so meta!)

### ISSUE THREAD

**Issue by afred** [samvera/samvera.github.io#102]
**Background:** per discussion during [meeting on 6/27/2017](https://wiki.duraspace.org/display/samvera/2017-06-27+Meeting+notes), we were wondering how to best handle content for different versions, that may be the same.

For instance:
  * If an instructional document is applicable to multiple versions, how do we convey that?
  * Do we have a single document, with all relevant versions somewhere in the front matter, or somewhere in the content with a standard format?
  * If a document is no longer relevant to the latest version, do we highlight it, and if so, how?
  * Do we want to keep the content DRY, or is it ok to have multiple versions of the same docs when they apply to different versions?

These are questions that we will answer over time, but this ticket is to create a page for putting those answers, once we decide on them.

**Done when:** We have the initials for a page that will server as the starting point for instructions tech writers on how to add/modify content for this repository, samvera.github.io.

**Comment by elrayle** [comment]
Related discussion about documentation for various versions of Hyrax and other stack components:  Issue #37

**Comment by elrayle** [comment]
The README has been updated as part of PR #103.  This includes some basic information about contributing documentation including descriptions of front matter, how to add terms to the a-z index.  

It can also be a place to...
* add information about how to add info, warning, and question boxes
* specify how to handle documentation for multiple versions of code

**Comment by afred** [comment]
closed by #112
