### ISSUE TITLE
Get community involvement on adding A - Z terms

### ISSUE THREAD

**Issue by jenlindner** [samvera/samvera.github.io#107]
Get community involvement on adding A - Z terms, and creating tickets for adding/modifying documentation content. This is very easy to do, and would help get newer devs familiar with the site. Notify slack #dev channel, email tech list, add it to tech call agenda, virtual connect and hydra connect.

**Done when:**

the following topics are presented to the community:
- [ ] A-Z index, and how to add pages
- [ ] Triggering new documentation tickets through slack, i.e. when you identify a missing page, make a ticket, optionally through slack channel.
... in the following venues...
- [ ] Hydra-tech mailing list
- [ ] Hydra-tech call on Wednesday 7/12/17
- [ ] Hydra virtual connect, Tues 7/18/17

**Comment by elrayle** [comment]
Relates to issue #104
