### ISSUE TITLE
Should we find and implement a search feature?

### ISSUE THREAD

**Issue by afred** [samvera/samvera.github.io#109]
Found this: https://learn.cloudcannon.com/jekyll/jekyll-search-using-lunr-js/

Let's look at it, and any others that might make a simple search index fairly straightforward.

**Done when:** we decide whether to use this tool, or a different one, and tickets are made to move forward with it.

**Comment by chrisdaaz** [comment]
is this still wanted? i've used lunr for another jekyll project and can look into adding search.

**Comment by RudyOnRails** [comment]
Sounds good to me, I plan to hit these docs pretty hard and search would be
great.

My 2 cents.

**Comment by chrisdaaz** [comment]
as an opportunity to learn something new, i attempted this but couldn't get the json index to build properly. if anyone's interested, i can share the branch i made. i'd definitely like to know what i did wrong.
