### ISSUE TITLE
Problems with "Formalities" page

### ISSUE THREAD

**Issue by laritakr** [samvera/samvera.github.io#115]
### Changes needed

- [x] 1. [Formalities page](http://samvera.github.io/formalities.html) is not included in sidebar menu
- [x] 2. Formalities page has a bad link to [communication channels page](http://samvera.github.io/communication.html)
- [x] 3. Front matter is not complete, and does not match location of page in the directory structure.
- [x] 4. The url for more details on duraspace site is not a link on the Formalities page, and is also incorrect. (addressed by #111)

**Comment by mjgiarlo** [comment]
#111 fixes the fourth change above.
