### ISSUE TITLE
Add a Code of Conduct for the community/developers/slack/etc

### ISSUE THREAD

**Issue by aaron-collier** [samvera/samvera.github.io#129]
### Descriptive summary of request

Should we adopt the Samvera Connect (or another) Code of Conduct into a formal code of conduct for developers/committers within the community?

### Existing Documentation

https://wiki.duraspace.org/display/samvera/Code+of+Conduct
https://github.com/samvera/hyrax/blob/master/.github/CODE_OF_CONDUCT.md

### Expected Document

While the above CoC is in the Duraspace wiki, I'm thinking we need to highlight it frequently within the rest of the documentation, but also it may need to be adjusted specifically for behavior within the dev community, submitting issues, PR conversations, etc.

**Comment by mjgiarlo** [comment]
@aaron-collier Updated the description above to link to the CoC as embedded in the Hyrax repo.

**Comment by aaron-collier** [comment]
@mjgiarlo Awesome. I was looking for that.

**Comment by mjgiarlo** [comment]
@aaron-collier If you're wondering how GitHub uses the CoC... here's one way: https://github.com/samvera/hyrax/community

**Comment by aaron-collier** [comment]
CoC linked in readme.
