### ISSUE TITLE
Add new left navigation for WorkFlow in Manager Guide and update text

### ISSUE THREAD

**Issue by julesies** [samvera/samvera.github.io#161]
### Descriptive summary of request
1. Add a new section for Workflow (sound okay @chrisdaaz ?)
2. Update text from Google Doc (is now ready!)
3. Remove Workflow placeholder text from Admin Sets

**Comment by chrisdaaz** [comment]
sounds good @julesies 

i separated these into #162 and #163 for easier tracking
