### ISSUE TITLE
Add new section for Workflows

### ISSUE THREAD

**Issue by chrisdaaz** [samvera/samvera.github.io#162]
### Descriptive summary of request

- [ ] Create a new section for the manager guide that focuses on workflows. 

### Clean-up
- [ ] Remove Workflow placeholder text from Admin Sets

**Comment by chrisdaaz** [comment]
assigning @julesies for now. does this documentation exist, or does it need to be written first? if it exists, can you put a link to it here?

**Comment by julesies** [comment]
@chrisdaaz it's here: https://docs.google.com/document/d/1q-8ewZDgjEN6e9sBLetaslfdc2M3xo63sKNvpcw-QgY/edit# 

scroll way down to "Mediated Deposit/Workflow WHOLE SECTION IS NEW" 

Is this fine or would you rather me paste stuff here?

**Comment by chrisdaaz** [comment]
@julesies perfect, thanks!

**Comment by chrisdaaz** [comment]
done with #163
