### ISSUE TITLE
Update Manager Guide from Google Doc

### ISSUE THREAD

**Issue by chrisdaaz** [samvera/samvera.github.io#163]
### Descriptive summary of request

Review [Google Doc](https://docs.google.com/document/d/1q-8ewZDgjEN6e9sBLetaslfdc2M3xo63sKNvpcw-QgY/edit#) and add new text to the manager guide.

**Comment by rjkati** [comment]
@chrisdaaz I've added a few things to the Administrative Sets and Mediated Deposit sections in the Google Doc.  My comments are in red.
