### ISSUE TITLE
Update Manager Guide: What's New in Hyrax 2.0?

### ISSUE THREAD

**Issue by gamontoya** [samvera/samvera.github.io#172]
### Descriptive summary of request

- http://samvera.github.io/whats-new.html

**The following updates and corrections are needed:**

- **Dashboard**
  - _Administrator and user functions used to be performed **through**..._
  - _In Hyrax 2, these were **consolidated**..._
  - _**Administrators** can query the repository..._ 
  - _The Configuration section is also a new addition to the Administrator **dashboard**._ 

- **Languages**
  - _The user interface can now be translated into seven languages: English, Spanish, German, French, Italian, **Portuguese**_

- **Metadata**
  - _Licenses and Rights Statements used to be ~~used to be~~ in the..._
### Tags

- Change to Documentation

**Comment by chrisdaaz** [comment]
thanks @gamontoya
