### ISSUE TITLE
Update Manager Guide: Concepts and Definitions

### ISSUE THREAD

**Issue by gamontoya** [samvera/samvera.github.io#173]
### Descriptive summary of request

http://samvera.github.io/concepts-2.0.html

The following updates and corrections are needed:

- **Collection:**
  - _A **thematic** grouping of works_

- **Mediated Deposit:**
  - _Commonly used in the context of **collecting** Electronic Theses_

- **Roles:**
  - _System Roles `(add line break here?)` Repository Administrator is the only system wide role_
  - _System Roles Repository Administrator is the only **system-wide** role_
  - _Collections & Administrative Set Participants `(add line break here?) `In addition to system roles_

### Tags

- Change to Documentation

**Comment by chrisdaaz** [comment]
thanks @gamontoya
