### ISSUE TITLE
A-Z index is perpetually regenerated when previewing the site

### ISSUE THREAD

**Issue by afred** [samvera/samvera.github.io#219]
Not a huge deal, but I noticed that the generation of the A-Z index seems to trigger Jekyll to rebuild the site, which triggers the re-generation of the A-Z index, which triggers Jekyll to rebuild the site....

**Done when:** the vicious cycle ends. Perhaps by telling Jeykyll not to trigger a rebuild when it detects changes to the A-Z index?

**Comment by hackmastera** [comment]
here's a branch trying it out: https://github.com/samvera/samvera.github.io/tree/fix-a-z-watch-loop

**Comment by afred** [comment]
maybe try moving the A-Z index building logic to a [Jekyll hook](https://jekyllrb.com/docs/plugins/#hooks) like so...
```ruby
Jekyll::Hooks.register :site, :post_write do |site|
  # generate a-z index directly to pages/a-z.md (instead of generate/a-z.md)
end
```
