### ISSUE TITLE
Add Rubocop training in the onboarding documentation

### ISSUE THREAD

**Issue by jcoyne** [samvera/samvera.github.io#22]
Suggestion from @jrochkind

Specifically "what do I do when rubocop says my code is wrong?"

This could include
- [ ] autofixing 
- [ ] disabling in source  code http://rubocop.readthedocs.io/en/latest/configuration/#disabling-cops-within-source-code
- [ ] using rubocop_todo.yml
- [ ] disabling cops for the whole project.

**Comment by jrochkind** [comment]
Where does one _find_ the onboarding docs again? I've seen it before, but can't seem to find it again now googling.

**Comment by bess** [comment]
@elrayle This has lots of overlap with what you're working on already, right?

**Comment by elrayle** [comment]
The exact questions that are asked here are part of the Best Practices: Coding Style document that is just about complete as part of Issue #61.

**Comment by elrayle** [comment]
Fixed by PR #77
