### ISSUE TITLE
Add page about Hyrax releases

### ISSUE THREAD

**Issue by afred** [samvera/samvera.github.io#246]
**Done when:** page is added outlining details regarding Hyrax releases, when they happen, how they happen, what to expect, etc.

NOTE: this ticket created as a result of getting rid of blank placeholder page in https://github.com/samvera/samvera.github.io/pull/239/

original frontmatter included:
```
categories: Community
```

**Comment by chrisdaaz** [comment]
@afred does this cover it? http://samvera.github.io/release_process.html

**Comment by afred** [comment]
@chrisdaaz yeah, I think so. I didn't realize there was already a page, so thanks! I think if we want additional content, we can create individual tickets.
