### ISSUE TITLE
Site Header URL Breaks After Performing Search

### ISSUE THREAD

**Issue by chrisdaaz** [samvera/samvera.github.io#315]
### Descriptive summary of request

After performing a search, the site header url changes to `http://samvera.github.io/search/index.html`

![image](https://user-images.githubusercontent.com/24395592/40558803-276db39e-601a-11e8-8ccc-19e6f96556cb.png)

Users likely expect the site header to be `http://samvera.github.io/index.html` in order to return to the homepage after performing a search.

**Comment by julesies** [comment]
Just adding, if you do a search, then click on the left hand menu pages you get a 404


example: http://samvera.github.io/search/communication.html
