### ISSUE TITLE
Add definitions for Fileset, Parent/Child works to glossary

### ISSUE THREAD

**Issue by julesies** [samvera/samvera.github.io#344]
### Descriptive summary of request

Prepping for a workshop for Samvera connect and notice we need definitions for Fileset and Parent/Child works in the glossary. I can write something up for review @chrisdaaz ?? 

http://samvera.github.io/glossary-2.1.html

**Comment by chrisdaaz** [comment]
@julesies yeah!

**Comment by julesies** [comment]
@elrayle does this look good to you? I used your def of fileset from the preso and added the parent/child stuff.
