### ISSUE TITLE
Update Core Components Page

### ISSUE THREAD

**Issue by tpendragon** [samvera/samvera.github.io#401]
- Add IIIF Manifest
- Remove Solrizer

**Comment by jrgriffiniii** [comment]
Please see https://samvera.github.io/core_components.html for reference.

**Comment by K8Sewell** [comment]
This issue appears complete on the site (screenshot below) and here's the commit that added IIIF - https://github.com/samvera/samvera.github.io/commit/a1af36230060e86d92a95c8701f84bc1cb78904d#diff-858696e65b1b2e2ae28f79f930f50537 - Should we go ahead and call this issue closed?

Core Component Table of Contents at present:
<img width="329" alt="image" src="https://user-images.githubusercontent.com/36549923/84431048-7c519700-abdf-11ea-9810-135f42847cd8.png">

**Comment by jrgriffiniii** [comment]
Verified as complete by @K8Sewell
