### ISSUE TITLE
Fix gem deployment issues

### ISSUE THREAD

**Issue by jenlindner** [samvera/samvera.github.io#48]
Hi @elrayle, the build failed in production with the gem in place. Would you like to tackle making it work there? It didn't generate useful error messages ("build failed"), and I put in a ticket to Github support about it. It's possible adding Travis would give us the verbosity we need to solve it.

**Comment by jenlindner** [comment]
A little more context -- the build doesn't fail locally with the gem. 

Users with admin access can choose a gh-pages branch for publishing, the best way to debug it might be to put the gem in a gh-pages branch along with Travis, and deploy, and hope to see specific build errors.

https://help.github.com/articles/troubleshooting-github-pages-builds/

**Comment by elrayle** [comment]
Additional info from @jenlindner...

> 'build in production' means...  pushing to master.
> 
> Users with admin access can choose a gh-pages branch for publishing, but I just have write access. It's showing up because I edited it to use the theme's source files, not the gem.
> 
> AFAICT, the best way to debug it would be to put the gem in a gh-pages branch along with Travis, and deploy. Travis might give better errors. Our current setup just emails, and the default error message is literally just "build failed." There's a gh pages jekyll troubleshooting page with common errors: https://help.github.com/articles/troubleshooting-github-pages-builds/, but we'd first have to see those errors. which we never see locally.

**Comment by elrayle** [comment]
Issue with overrides is being discussed in...  https://github.com/tomjohnson1492/documentation-theme-jekyll/issues/45
