### ISSUE TITLE
Incorporate style guide into the coding best practices docs

### ISSUE THREAD

**Issue by aaron-collier** [samvera/samvera.github.io#80]
### Descriptive summary of request

Add https://github.com/projecthydra/sufia/wiki/Coding-Conventions information to http://projecthydra.github.io/best-practices-coding-styles.html

**Comment by mjgiarlo** [comment]
That Sufia wiki page is super out of date. You might want something more like: https://github.com/escowles/technical-onboarding/blob/master/code.md#style-guidelines

**Comment by elrayle** [comment]
There is a page in the doc around styles, specifically to using rubocop...

http://samvera.github.io/best-practices-coding-styles.html

Do you want more information?
